name: LBG PE Pipeline Generator

'on':
  push:
    branches:
    - main
  workflow_dispatch:
      inputs: 
        value:
          required: true
          type: string
          default : "{'repository_user': 'mayankagarwal19911', 'repository_name':'lbg-statestreet-mortgage','client_id':'7500907','namespace_name':'statestreet_mortgage','template_repository_path':'https://github.com/learnk8s/docker-hello-world','description':'Borrower and Loan Use Description.', 'email': 'mayank.agarwal19911@gmail.com'}"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate Template
      run: python PipelineGenerator.py "echo ${{ github.event.inputs.value }}"

