name: LBG PE Pipeline Generator

'on':
  push:
    branches:
    - main
  workflow_dispatch:
      inputs: 
        value:
          required: true
          type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: '${{ secrets.GH_TOKEN }}'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r python-scripts/requirements.txt; fi
    - name: Running Pipeline Generator Python Script
      run: python python-scripts/pipelinegenerator.py "${{ github.event.inputs.value }}" "${{ secrets.GH_TOKEN }}"
  
